
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
decorations = "Full"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dimensions = {columns = 120, lines = 35}



[general]
import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]

[terminal]
